[phases.setup]
nixPkgs = ["python310", "opencv", "tesseract", "libgl", "libglib", "libsm", "libxext", "libxrender", "libgomp", "libgthread-2.0-0"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
