[phases.setup]
nixPkgs = ["python310", "opencv", "tesseract"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
